**OpenAI Gym: Carpole simple example (random actions)**

In [2]:
import gym

!pip install "numpy<2" --quiet
import numpy as np
print("NumPy version:", np.__version__)  # should be 1.26.x

1- Create the environment and test it

In [4]:
env = gym.make("CartPole-v1")
obs = env.reset()
obs

array([ 0.00212073, -0.0017784 , -0.00645734,  0.0453412 ], dtype=float32)

2- Explore Action space

In [5]:
env.action_space # Possible actions: 0 (left), 1 (right)

Discrete(2)

3- Explore Observation space

In [8]:
env.observation_space # Obsrvation: [x, x', theta, theta']

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)

4- Push platform to the left

In [9]:
env.step(0)

(array([-0.00185098, -0.3918497 ,  0.00116908,  0.6269072 ], dtype=float32),
 1.0,
 False,
 {})

5- Sample random action

In [17]:
env.action_space.sample()

1

6- Sample random observation

In [19]:
env.observation_space.sample()

array([-4.6132016e+00,  7.2993147e+37, -1.1592893e-01,  8.6243807e+37],
      dtype=float32)

7- Implement a loop with random actions

In [25]:
total_reward = 0.0
total_steps = 0
obs = env.reset()

while True:
    action = env.action_space.sample() # take a random action
    obs, reward, done, _ = env.step(action) # execute one step
    total_reward += reward
    total_steps += 1
    if done:
        break

print("Episode done in %d steps, total reward %.2f" % (
    total_steps, total_reward))


Episode done in 24 steps, total reward 24.00
